export const groups = [
  {
    title: "Group 1: Legendary",
    highlight: true,
    supply: 130,
    tokensMinted: 103,
    imageURL: "/Group 1.jpg",
    soldOut: false,
    available: true,
    discount: 50,
    tokenName: "Legendary",
    hasFakeIDDiscount: false,
  },
  {
    title: "Group 2: Redlist Gold",
    highlight: true,
    supply: 150,
    tokensMinted: 100,
    imageURL: "/Group 2.jpg",
    soldOut: false,
    available: true,
    discount: 20,
    tokenName: "Redlist Gold",
    hasFakeIDDiscount: true,
  },
  {
    title: "Group 3: Redlist Steel",
    highlight: false,
    supply: 250,
    tokensMinted: 0,
    imageURL: "/Group 3.jpg",
    soldOut: false,
    available: false,
    discount: 15,
    tokenName: "Redlist Steel",
    hasFakeIDDiscount: true,
  },
  {
    title: "Group 4: Redlist Black",
    highlight: true,
    supply: 300,
    tokensMinted: 0,
    imageURL: "/Group 4.jpg",
    soldOut: false,
    available: true,
    discount: 10,
    tokenName: "Redlist Black",
    hasFakeIDDiscount: true,
  },
  {
    title: "Group 5: Fake ID Holders",
    highlight: false,
    supply: 500,
    tokensMinted: 0,
    imageURL: "/Group 5.jpg",
    soldOut: false,
    available: true,
    discount: 10,
    tokenName: "Fake ID",
    hasFakeIDDiscount: false,
  },
  {
    title: "Group 6: Open Mint",
    highlight: false,
    supply: 666,
    tokensMinted: 0,
    imageURL: "/Group 6.jpg",
    soldOut: false,
    available: true,
    discount: 0,
    tokenName: "",
    hasFakeIDDiscount: false,
  },
];
